spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713840463994-mv87bjvam3eoidjo060h4elt4emb7m57.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile