spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 176209800309-b114i94scrb4ao5dtrqbqgra55lrsm8i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

