spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 0000
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    include: oauth
  mustache:
    # 1. request attribute 의 내용을 model에 추가
    expose-request-attributes: true
    # 2. session attribute 의 내용을 model에 추가
    expose-session-attributes: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false

