spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    include:
      - oauth
      - mail
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기

kakao:
  admin:
    key: bd19866f3ada589ede420687d2af3d3a
  host: https://kapi.kakao.com
  uri:
    pay-process: /api/purchase
  pay:
    ready: /v1/payment/ready
    approve: /v1/payment/approve
    cid: TC0ONETIME
    regularCid: TCSUBSCRIP
    taxfree: 1000
    cancel: /v1/payment/cancel
    order: /v1/payment/order

toss:
  secret-key: test_sk_ZORzdMaqN3wpY7eD47bV5AkYXQGw

pay:
  request-url: http://localhost:8080

cloud:
  aws:
    s3:
      bucket: fruit-fruit-image
    credentials:
      accessKey: AKIAU5GCOHQLTUSU4KWA
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
