spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    include:
      - oauth
      - mail
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false

kakao:
  admin:
    key: bd19866f3ada589ede420687d2af3d3a
  host: https://kapi.kakao.com
  uri:
    pay-process: /api/purchase
  pay:
    ready: /v1/payment/ready
    approve: /v1/payment/approve
    cid: TC0ONETIME
    taxfree: 1000
    cancel: /v1/payment/cancel
    order: /v1/payment/order

toss:
  secret-key: test_sk_ZORzdMaqN3wpY7eD47bV5AkYXQGw

pay:
  request-url: http://localhost:8080